# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant multi-machine sample setup

Vagrant.configure("2") do |config|
  config.vm.define :alpha do |alpha|
    alpha.vm.box = "ubuntu/bionic64"
    alpha.vm.network :private_network, ip: "192.168.56.12"
    alpha.vm.network "forwarded_port", guest: 8080, host: 8080
    alpha.vm.hostname = "alpha"
    alpha.vm.provider "virtualbox" do |v|
      v.name = "alpha"
     end
    alpha.vm.provision "shell" do |s|
      s.path = 'alpha.sh'
    end
  end

  config.vm.define :beta do |beta|
    beta.vm.box = "ubuntu/bionic64"
    beta.vm.network :private_network, ip: "192.168.56.14"
    beta.vm.network "forwarded_port", guest: 8090, host: 8090
    beta.vm.hostname = "beta"
    beta.vm.provider "virtualbox" do |v|
      v.name = "beta"
     end
    beta.vm.provision "shell" do |s|
      s.path = 'beta.sh'
    end
  end
end